### ISSUE TITLE
`smithy format` puts postfix inline comments in the wrong place

### ISSUE THREAD

**Issue by rhernandez35** [smithy-lang/smithy#2431] opened 2024-10-24 01:14 UTC
`smithy format` will turn this:

```
operation Demo {
    input: Unit // No input
    output := {
        foo: String
    }
}
```

into this:

```
operation Demo {
    input: Unit

    // No input
    output := {
        foo: String
    }
}
```

I would expect a trailing comment to adorn the syntactical element it's sharing a line with and not with the element following it.

**Comment by tripplilley** [comment] 2024-10-31 17:33
Possible duplicate of #2279

**Comment by kstich** [comment] 2024-11-05 19:11
Correct, closing as a duplicate of #2279

**Closed by kstich** 2024-11-05 19:11 UTC
Labels: bug
